version: '3.8'

services:
  tauri-app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /tmp/.X11-unix:/tmp/.X11-unix 
    ports:
      - "3000:3000"
    environment:
      - DISPLAY=${DISPLAY} 
      - RUST_LOG=debug
    working_dir: /app
    stdin_open: true
    tty: true
